name: tattoo
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - pip:
      - ollama
      - langchain
      - langchain-ollama
      - streamlit
      - pillow
